export const UPDATE_FROMDB = 'UPDATE_FROMDB';
export const UPDATE_CHAT_FROMDB = 'UPDATE_CHAT_FROMDB';
export const SELECT_ROOM = 'SELECT_ROOM';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
